accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'login/$', views.sign_in),
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.profile, name='profile'),
    url(r'profile_crop/$', views.profile_crop, name='profile_crop'),
    url(r'profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'profile/password_change/$',
        views.password_change, name='password_change'),
    url(r'$', views.profile),
]

project_7/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
    url(r'^tinymce/', include('tinymce.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from tinymce.models import HTMLField


class UserProfile(models.Model):
    """User Profile, one to one relationship with users"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=64, blank=True)
    last_name = models.CharField(max_length=64, blank=True)
    email = models.CharField(max_length=64, blank=True)
    date_of_birth = models.DateTimeField(null=True, blank=True)
    short_bio = HTMLField(blank=True)
    avatar = models.ImageField(blank=True)
    # Extra Credit
    city = models.CharField(max_length=64, blank=True)
    state = models.CharField(max_length=64, blank=True)
    country = models.CharField(max_length=64, blank=True)
    favorite_animal = models.CharField(max_length=64, blank=True)
    hobby = models.CharField(max_length=64, blank=True)

    class Meta:
        ordering = ['user', ]

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


# Create an empty profile when the user is created
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

accounts/forms.py
import re

from datetime import timedelta
from django import forms
from . import models
from tinymce.widgets import TinyMCE

# Regex pattern to insure, conatins, lower, upprt, numeric and special
# characters and is at least 14 characters long and no spaces
pattern = ("^(?=.*?\d)(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#*$@!%])" +
           "[A-Za-z0-9#*@$!%\d]{14,}$")
password_regex = re.compile(pattern)


# Function to claer all <> tags
def removetags(raw):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw)
    return cleantext


class ProfileForm(forms.ModelForm):
    email = forms.EmailField()
    confirm_email = forms.CharField(required=False)
    date_of_birth = forms.DateField(input_formats=['%Y-%m-%d',
                                                   '%m/%d/%Y',
                                                   '%m/%d/%y'],
                                    widget=forms.DateInput(format='%Y-%m-%d'))
    short_bio = forms.CharField(widget=TinyMCE(attrs={'rows': 10}),
                                min_length=10)
    avatar = forms.ImageField(required=False)

    class Meta:
        model = models.UserProfile
        fields = [
            'first_name',
            'last_name',
            'email',
            'confirm_email',
            'date_of_birth',
            'short_bio',
            'avatar',
            'city',
            'state',
            'country',
            'favorite_animal',
            'hobby',
        ]

    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        # Check date is in the Past
        date_of_birth = cleaned_data.get("date_of_birth")
        if date_of_birth.year > 2020:
            adjusted_date = date_of_birth - timedelta(days=36524.25)
            cleaned_data["date_of_birth"] = adjusted_date

        # Work around formatted text length
        short_bio = cleaned_data.get("short_bio")
        if short_bio is None or len(removetags(short_bio)) < 10:
            raise forms.ValidationError("Your Bio must be at least 10 " +
                                        "characters long.")

        # Check email match
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")

        if email != confirm_email:
            raise forms.ValidationError(
                "email and confirm email do not match")

        return cleaned_data


class PasswordChangeCustomForm(forms.Form):
    current_password = forms.CharField(required=True,
                                       widget=forms.PasswordInput())
    new_password = forms.CharField(required=True,
                                   widget=forms.PasswordInput(
                                    attrs={'data-indicator': 'pwindicator'}),
                                   min_length=14)
    confirm_password = forms.CharField(required=True,
                                       widget=forms.PasswordInput(),
                                       min_length=14)

    # Override init to get user and profile
    def __init__(self, data=None, user=None, profile=None, *args, **kwargs):
        self.user = user
        self.profile = profile
        super(PasswordChangeCustomForm, self).__init__(data=data,
                                                       *args, **kwargs)

    def clean(self):
        cleaned_data = super(PasswordChangeCustomForm, self).clean()

        current_password = cleaned_data.get("current_password")
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        # Check current password is correct
        if not self.user.check_password(current_password):
            raise forms.ValidationError('incorrect current password')

        # Check password does not equal current password
        if new_password == current_password:
            raise forms.ValidationError(
                "new password cannot be same as current password")

        # Check password contains:
        # Uppercase, lowercase, numeric and from @ # $
        if re.match(password_regex, new_password) is None:
            raise forms.ValidationError(
                "new password must contain, both upper and lowercase " +
                "letters, numbers and characters from #*$@!%, but no spaces")

        # Check password does not contain, first, last or usernames
        if ((self.profile.first_name.lower() != '' and
                self.profile.first_name.lower() in new_password.lower()) or
                (self.profile.last_name.lower() != '' and
                 self.profile.last_name.lower() in new_password.lower()) or
                self.user.username.lower() in new_password.lower()):
            raise forms.ValidationError(
                "password cannot contain your username, firstname or lastname")

        # Check new passwords match
        if new_password != confirm_password:
            raise forms.ValidationError(
                "new and confirm passwords do not match")

        return cleaned_data


class CropForm(forms.Form):
    """ Hide a fields to hold the coordinates chosen by the user """
    scale = forms.CharField(widget=forms.Textarea(
        attrs={'style': 'display:none'}))
    angle = forms.CharField(widget=forms.Textarea(
        attrs={'style': 'display:none'}))
    x = forms.CharField(widget=forms.Textarea(attrs={'style': 'display:none'}))
    y = forms.CharField(widget=forms.Textarea(attrs={'style': 'display:none'}))
    w = forms.CharField(widget=forms.Textarea(attrs={'style': 'display:none'}))
    h = forms.CharField(widget=forms.Textarea(attrs={'style': 'display:none'}))

accounts/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from PIL import Image

from . import forms


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(
                        reverse('accounts:profile')
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            return HttpResponseRedirect(reverse('accounts:profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def profile(request):
    current_user = request.user
    profile = request.user.userprofile
    return render(request, 'accounts/profile.html',
                  {'current_user': current_user, 'profile': profile})


@login_required
def profile_edit(request):
    current_user = request.user
    form = forms.ProfileForm(instance=request.user.userprofile)

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, request.FILES or None,
                                 instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was successfully updated!')
            if len(request.FILES) != 0:
                # preprocess uploaded image
                new_image = str(request.user.userprofile.avatar.file)
                im = Image.open(new_image)
                # Resize to manageable
                im.thumbnail((400, 600), Image.ANTIALIAS)
                im.save(new_image)

                # Redirect to cropping
                return HttpResponseRedirect(reverse('accounts:profile_crop'))

            return HttpResponseRedirect(reverse('accounts:profile'))

    return render(request, 'accounts/profile_edit.html',
                  {'form': form, 'current_user': current_user})


@login_required
def password_change(request):
    form = forms.PasswordChangeCustomForm()
    user = request.user
    if request.method == 'POST':
        form = forms.PasswordChangeCustomForm(data=request.POST, user=user,
                                              profile=user.userprofile)
        if form.is_valid():
            user.set_password(form.cleaned_data['new_password'])
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request,
                             'Your password was successfully changed!')
            return HttpResponseRedirect(reverse('home'))

    return render(request, 'accounts/password_change.html', {'form': form})


@login_required
def profile_crop(request):
    form = forms.CropForm()
    user = request.user
    profile = request.user.userprofile
    if request.method == 'POST':
        form = forms.CropForm(data=request.POST)
        if form.is_valid():
            original_image = str(profile.avatar.file)
            crop_coords = {
                'scale': float(form.cleaned_data['scale']),
                'angle': 0 - float(form.cleaned_data['angle']),
                'x': float(form.cleaned_data['x']),
                'y': float(form.cleaned_data['y']),
                'w': float(form.cleaned_data['w']),
                'h': float(form.cleaned_data['h'])
            }
            cropper(original_image, crop_coords)
            return render(request, 'accounts/profile.html',
                          {'current_user': user, 'profile': profile})

    return render(request, 'accounts/profile_crop.html',
                  {'user': user, 'profile': profile, 'form': form})


def cropper(original_image_path, crop_coords):
    """ Open original, create and save a new cropped image"""
    editable = Image.open(original_image_path)

    # rotate first
    if crop_coords['angle'] != 0:
        editable = editable.rotate(crop_coords['angle'], expand=True)

    # cropping area
    box = (int(crop_coords['x']/crop_coords['scale']),
           int(crop_coords['y']/crop_coords['scale']),
           int((crop_coords['x'] + crop_coords['w'])/crop_coords['scale']),
           int((crop_coords['y'] + crop_coords['h'])/crop_coords['scale']))
    editable = editable.crop(box)

    # save over original_image_path
    editable.save(original_image_path)

accounts/templates/accounts/password_change.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Change Password{% endblock %}

{% block css %}

{% endblock %}
{% block js %}
<script type="text/javascript"
        src="{% static "js/jquery.pwstrength.js" %}"></script>
<script type="text/javascript">
    jQuery(function($) { $('#id_new_password').pwstrength(); });
</script>
{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:password_change' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.current_password.errors }}
        <label for="{{ form.current_password.id_for_label }}">Current Password:</label>
        {{ form.current_password }}
    </div>
    <div>
        <ul class="nonfield">
            <li><strong>New password my be at least 14 characters and contain:</strong></li>
            <li>Lower and uppercase letters</li>
            <li>Number characters</li>
            <li>At least one chaacter from: #*@$!%</li>
            <li>No spaces</li>
            <li>Not your first, last or username</li>
        </ul>
    </div>
    <div class="fieldWrapper">
        {{ form.new_password.errors }}
        <label for="{{ form.new_password.id_for_label }}">New Password:</label>
        {{ form.new_password }}
    </div>
    <div id="pwindicator">
        <div class="bar"></div>
        <div class="label"></div>
    </div>
    <div class="fieldWrapper">
        {{ form.confirm_password.errors }}
        <label for="{{ form.confirm_password.id_for_label }}">Confirm Password:</label>
        {{ form.confirm_password }}
    </div>
    <input type="submit" class="button-primary" value="Save New Password">
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "layout.html" %}

{% block title %}Profile | {{ current_user.username }}{% endblock %}

{% block body %}
<p><label for="username">Username:</label> {{ current_user.username }}</p>
<p><label for="date_joined">Date Joined:</label> {{ current_user.date_joined }}</p>
<p><label for="first_name">First Name:</label> {{ profile.first_name }}</p>
<p><label for="last_name">Last Name:</label> {{ profile.last_name }}</p>
<p><label for="email">Email:</label> {{ profile.email }}</p>
<p><label for="date_of_birth">Date Of Birth:</label> {{ profile.date_of_birth|date:"D d M Y" }}</p>
<p><label for="short_bio">Bio:</label> {{ profile.short_bio | safe }}</p>
<p><label for="avatar">Avatar:</label>
    {% if profile.avatar %}
    <img class="avatar" src="{{ profile.avatar.url }}" alt="{{ profile.avatar.name }}"></br>
    <a class="button-link" href="{% url 'accounts:profile_crop' %}">Crop Avatar</a>
    {% endif %}
</p>
<p><label for="city">City:</label> {{ profile.city }}</p>
<p><label for="state">State:</label> {{ profile.state }}</p>
<p><label for="country">Country:</label> {{ profile.country }}</p>
<p><label for="favorite_animal">Favorite Animal:</label> {{ profile.favorite_animal }}</p>
<p><label for="hobby">Hobby:</label> {{ profile.hobby }}</p>
<p><a class="button-link" href="{% url 'accounts:profile_edit' %}">Edit Profile</a></p>
{% endblock %}

accounts/templates/accounts/profile_crop.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Edit Profile | {{ user.username }}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static "css/jquery.guillotine.css" %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="{% static "js/jquery.guillotine.js" %}"></script>
<script>
jQuery(function() {
  var picture = $('#avatar');

  // Make sure the image is completely loaded before calling the plugin
  picture.one('load', function(){
    // Initialize plugin (with custom event)
    picture.guillotine({eventOnChange: 'guillotinechange', width: 300, height: 400});

    // Display inital data
    var data = picture.guillotine('getData');
    for(var key in data) { $('#id_'+key).text(data[key]); }

    // Bind button actions
    $('#rotate_left').click(function(){ picture.guillotine('rotateLeft'); });
    $('#rotate_right').click(function(){ picture.guillotine('rotateRight'); });
    $('#zoom_in').click(function(){ picture.guillotine('zoomIn'); });
    $('#zoom_out').click(function(){ picture.guillotine('zoomOut'); });

    // Update data on change
    picture.on('guillotinechange', function(ev, data, action) {
      data.scale = parseFloat(data.scale.toFixed(4));
      for(var key in data) { $('#id_'+key).text(data[key]); }
    });
  });

  // Make sure the 'load' event is triggered at least once (for cached images)
  if (picture.prop('complete')) picture.trigger('load')
});
</script>
{% endblock %}

{% block body %}
<h1>Crop your avatar</h1>
{% if profile.avatar %}
<div id='content'>

  <div class='frame'>
    <img id='avatar' src='{{ profile.avatar.url }}'>
  </div>

  <div id='controls'>
    <button id='rotate_left'  type='button' title='Rotate left'> &lt; </button>
    <button id='zoom_out'     type='button' title='Zoom out'> - </button>
    <button id='zoom_in'      type='button' title='Zoom in'> + </button>
    <button id='rotate_right' type='button' title='Rotate right'> &gt; </button>
  </div>
</div>
<form method="POST" action="{% url 'accounts:profile_crop' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.scale }}
    {{ form.angle }}
    {{ form.x }}
    {{ form.y }}
    {{ form.w }}
    {{ form.h }}
    <input type="submit" class="button-primary" value="Save">
</form>

{% else %}
<h2>No avatar uploaded yet</h2>
{% endif %}
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Edit Profile | {{ current_user.username }}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static "css/font_roboto/roboto.css" %}">
<link rel="stylesheet" href="{% static "css/dhtmlxcalendar.css" %}">
{% endblock %}
{% block js %}
<script type="text/javascript"
        src="{% static "js/dhtmlxcalendar.js" %}"></script>

<script>
var myCalendar;
window.onload = function() {
    myCalendar = new dhtmlXCalendarObject(["id_date_of_birth"]);
};
</script>
{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:profile_edit' %}" enctype="multipart/form-data">
    <p><label for="username">Username:</label> {{ current_user.username }}</p>
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" class="button-primary" value="Save">
</form>
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}