accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'login/$', views.sign_in),
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.profile, name='profile'),
    url(r'profile_crop/$', views.profile_crop, name='profile_crop'),
    url(r'profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'profile/password_change/$',
        views.password_change, name='password_change'),
    url(r'$', views.profile),
]

project_7/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
    url(r'^tinymce/', include('tinymce.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-25">
        nav here maybe?
    </div>
    <div class="grid-75">
        <h1>Welcome!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad amet assumenda beatae blanditiis, deserunt doloremque ea earum excepturi id, impedit ipsam magnam nulla obcaecati, quidem quis soluta tenetur vitae?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad amet assumenda beatae blanditiis, deserunt doloremque ea earum excepturi id, impedit ipsam magnam nulla obcaecati, quidem quis soluta tenetur vitae?</p>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">
    <link rel="stylesheet" href="{% static "css/variables.css" %}">
    {% block css %}{% endblock %}

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>
    {% block js %}{% endblock %}

    {{ form.media }}
</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        <li><a href="{% url 'accounts:profile' %}">My Profile</a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:profile_edit' %}">Edit Profile</a></li>
                            <li><a href="{% url 'accounts:password_change' %}">Change Password</a></li>
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>